FROM lscr.io/linuxserver/kali-linux:latest

EXPOSE 3000

# RUN apt-get -y install coreutils
RUN echo export GDK_SCALE=2 >> ~/.xsessionrc
RUN echo export QT_SCALE_FACTOR=2 >> ~/.xsessionrc
RUN echo export XCURSOR_SIZE=48 >> ~/.xsessionrc
ENV GDK_SCALE=2 \
    QT_SCALE_FACTOR=2 \
    XCURSOR_SIZE=48 \
    GDK_DPI_SCALE=0.5

RUN apt update
RUN apt install net-tools -y
RUN apt install wireshark -y
RUN apt install ettercap-graphical -y
RUN apt install nmap -y


