FROM kalilinux/kali-rolling

# Install openssh and a minimal kali metapackage
RUN apt-get update && apt-get install -y \
    openssh-server \
    net-tools \
    frr \
    && rm -rf /var/lib/apt/lists/*

# Create privilege separation directory
RUN mkdir /run/sshd || true

RUN echo 'root:kali' | chpasswd

RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D", "-e"]